# Ooyama Yosiyuki <qqke6wd9k@apricot.ocn.ne.jp>, 2015. #zanata
# Ooyama Yosiyuki <qqke6wd9k@apricot.ocn.ne.jp>, 2017. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-11-03 21:47-0500\n"
"PO-Revision-Date: 2017-07-01 03:51+0000\n"
"Last-Translator: Ooyama Yosiyuki <qqke6wd9k@apricot.ocn.ne.jp>\n"
"Language-Team: Japanese\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"X-Generator: Zanata 4.6.2\n"

#: ../plugins/showvars.py:46
msgid "show all active dnf variables"
msgstr ""

#: ../plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr ""

#: ../plugins/kickstart.py:60
msgid "Install packages defined in a kickstart file on your system"
msgstr ""

#: ../plugins/kickstart.py:65
msgid "kickstart file"
msgstr ""

#: ../plugins/kickstart.py:83
#, python-format
msgid "file cannot be parsed: %s"
msgstr "ファイルがパースできません: %s"

#: ../plugins/rpm_conf.py:65
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr ""

#: ../plugins/rpm_conf.py:71
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr ""

#: ../plugins/rpm_conf.py:84
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr ""

#: ../plugins/rpm_conf.py:88
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr ""

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:45
msgid "the color of the sky"
msgstr ""

#: ../plugins/system_upgrade.py:61
msgid "Need a --releasever greater than the current system version."
msgstr "--releasever は、現在のシステムのバージョン番号よりも大きくなければなりません。"

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:63
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade.\n"
"To remove cached metadata and transaction use 'dnf system-upgrade clean'"
msgstr ""

#: ../plugins/system_upgrade.py:66
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr ""

#: ../plugins/system_upgrade.py:119
#, python-format
msgid "Screen blanking can't be disabled: %s"
msgstr ""

#: ../plugins/system_upgrade.py:140
#, python-format
msgid "Failed loading state file: %s, continuing with empty state."
msgstr ""

#: ../plugins/system_upgrade.py:277
msgid "The following boots appear to contain upgrade logs:"
msgstr ""

#: ../plugins/system_upgrade.py:287
msgid "-- no logs were found --"
msgstr ""

#: ../plugins/system_upgrade.py:302
msgid "Cannot find logs with this index."
msgstr ""

#: ../plugins/system_upgrade.py:311
msgid "Unable to match systemd journal entry"
msgstr ""

#: ../plugins/system_upgrade.py:330
msgid "Prepare system for upgrade to a new release"
msgstr "システムに新リリースにアップグレードするための準備をしてください"

#: ../plugins/system_upgrade.py:340
msgid "keep installed packages if the new release's version is older"
msgstr ""

#: ../plugins/system_upgrade.py:344
msgid "which logs to show"
msgstr ""

#: ../plugins/system_upgrade.py:401
msgid "Additional information for System Upgrade: {}"
msgstr ""

#: ../plugins/system_upgrade.py:404
msgid ""
"Before you continue ensure that your system is fully upgraded by running "
"\"dnf --refresh upgrade\". Do you want to continue"
msgstr ""

#: ../plugins/system_upgrade.py:408
msgid "Operation aborted."
msgstr ""

#: ../plugins/system_upgrade.py:472
msgid "system is not ready for upgrade"
msgstr "システムはアップグレードの準備ができてません。"

#: ../plugins/system_upgrade.py:474
msgid "upgrade is already scheduled"
msgstr "アップグレードは既に予定されています"

#: ../plugins/system_upgrade.py:480
msgid "trigger file does not exist. exiting quietly."
msgstr ""

#: ../plugins/system_upgrade.py:483
msgid "another upgrade tool is running. exiting quietly."
msgstr ""

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:489
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr ""

#: ../plugins/system_upgrade.py:506
msgid "Rebooting to perform upgrade."
msgstr ""

#: ../plugins/system_upgrade.py:528 ../plugins/system_upgrade.py:534
msgid "Starting system upgrade. This will take a while."
msgstr "system upgrade を起動中。しばらく時間がかかります。"

#: ../plugins/system_upgrade.py:559 ../plugins/system_upgrade.py:568
#, python-format
msgid "Unable to match package: %s"
msgstr ""

#: ../plugins/system_upgrade.py:573
msgid "Unable to match some of packages"
msgstr ""

#: ../plugins/system_upgrade.py:576
msgid "Cleaning up downloaded data..."
msgstr "ダウンロード済みデータを掃除しています..."

#: ../plugins/system_upgrade.py:623
msgid "Download finished."
msgstr ""

#: ../plugins/system_upgrade.py:627 ../plugins/system_upgrade.py:628
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "アップグレードは完了しました！ 掃除と再起動中..."

#: ../plugins/tracer.py:70
msgid "For more information run:"
msgstr ""

#: ../plugins/tracer.py:97
msgid "Call to Tracer API ended unexpectedly:"
msgstr ""

#: ../plugins/tracer.py:99
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""

#: ../plugins/tracer.py:101
msgid "We apologize for any inconvenience"
msgstr "ご不便をお掛けして申し訳ございません"

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr ""

#: ../plugins/snapper.py:55
msgid "creating pre_snapshot"
msgstr ""

#: ../plugins/snapper.py:61
#, python-format
msgid "created pre_snapshot %d"
msgstr ""

#: ../plugins/snapper.py:65
#, python-format
msgid "creating pre_snapshot failed: %s"
msgstr ""

#: ../plugins/snapper.py:74
msgid "skipping post_snapshot because creation of pre_snapshot failed"
msgstr ""

#: ../plugins/snapper.py:80
msgid "creating post_snapshot"
msgstr ""

#: ../plugins/snapper.py:85
#, python-format
msgid "created post_snapshot %d"
msgstr ""

#: ../plugins/snapper.py:89
#, python-format
msgid "creating post_snapshot failed: %s"
msgstr ""
