# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Piotr Drąg <piotrdrag@gmail.com>, 2015
# Piotr Drąg <piotrdrag@gmail.com>, 2015. #zanata
# Piotr Drąg <piotrdrag@gmail.com>, 2016. #zanata
# Piotr Drąg <piotrdrag@gmail.com>, 2017. #zanata
# Piotr Drąg <piotrdrag@gmail.com>, 2018. #zanata
# Piotr Drąg <piotrdrag@gmail.com>, 2019. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-11-03 21:47-0500\n"
"PO-Revision-Date: 2019-10-19 12:06+0000\n"
"Last-Translator: Piotr Drąg <piotrdrag@gmail.com>\n"
"Language-Team: Polish (http://www.transifex.com/projects/p/dnf-plugins-extras/language/pl/)\n"
"Language: pl\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
"X-Generator: Zanata 4.6.2\n"

#: ../plugins/showvars.py:46
msgid "show all active dnf variables"
msgstr "wyświetla wszystkie aktywne zmienne DNF"

#: ../plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr "Wyłączanie wtyczki torproxy: nie można połączyć z siecią Tor"

#: ../plugins/kickstart.py:60
msgid "Install packages defined in a kickstart file on your system"
msgstr "Instaluje pakiety podane w pliku kickstart w systemie"

#: ../plugins/kickstart.py:65
msgid "kickstart file"
msgstr "plik kickstart"

#: ../plugins/kickstart.py:83
#, python-format
msgid "file cannot be parsed: %s"
msgstr "nie można przetworzyć pliku: %s"

#: ../plugins/rpm_conf.py:65
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr "Dodawanie „{}” do listy obsługiwanych pakietów dla rpmconf"

#: ../plugins/rpm_conf.py:71
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr "Wtyczka rpmconf nie będzie działała w trybie nieinteraktywnym"

#: ../plugins/rpm_conf.py:84
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr "ignorowanie sys.exit z rpmconf z powodu braku zmiennej „MERGE”"

#: ../plugins/rpm_conf.py:88
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr "ignorowanie sys.exit z rpmconf z powodu braku pliku"

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:45
msgid "the color of the sky"
msgstr "kolor nieba"

#: ../plugins/system_upgrade.py:61
msgid "Need a --releasever greater than the current system version."
msgstr ""
"Parametr „--releasever” wymaga wartości wyższej niż wersja obecnego systemu."

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:63
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade.\n"
"To remove cached metadata and transaction use 'dnf system-upgrade clean'"
msgstr ""
"Ukończono pobieranie. Polecenie „dnf system-upgrade reboot” rozpocznie aktualizację systemu.\n"
"Do usunięcia metadanych i transakcji z pamięci podręcznej można użyć polecenia „dnf system-upgrade clean”."

#: ../plugins/system_upgrade.py:66
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr "Należy użyć opcji „download --releasever” zamiast „--network”"

#: ../plugins/system_upgrade.py:119
#, python-format
msgid "Screen blanking can't be disabled: %s"
msgstr "Nie można wyłączyć wygaszania ekranu: %s"

#: ../plugins/system_upgrade.py:140
#, python-format
msgid "Failed loading state file: %s, continuing with empty state."
msgstr ""
"Wczytanie pliku stanu się nie powiodło: %s, kontynuowanie z pustym stanem."

#: ../plugins/system_upgrade.py:277
msgid "The following boots appear to contain upgrade logs:"
msgstr "Następujące uruchomienia zawierają dzienniki aktualizacji:"

#: ../plugins/system_upgrade.py:287
msgid "-- no logs were found --"
msgstr "-- nie odnaleziono dzienników --"

#: ../plugins/system_upgrade.py:302
msgid "Cannot find logs with this index."
msgstr "Nie można odnaleźć dzienników za pomocą tego indeksu."

#: ../plugins/system_upgrade.py:311
msgid "Unable to match systemd journal entry"
msgstr "Nie można dopasować wpisu dziennika systemd"

#: ../plugins/system_upgrade.py:330
msgid "Prepare system for upgrade to a new release"
msgstr "Przygotowuje system do aktualizacji do nowego wydania"

#: ../plugins/system_upgrade.py:340
msgid "keep installed packages if the new release's version is older"
msgstr ""
"zachowuje zainstalowane pakiety, jeśli wersja nowego wydania jest starsza"

#: ../plugins/system_upgrade.py:344
msgid "which logs to show"
msgstr "które dzienniki wyświetlić"

#: ../plugins/system_upgrade.py:401
msgid "Additional information for System Upgrade: {}"
msgstr "Dodatkowe informacje dla aktualizacji systemu: {}"

#: ../plugins/system_upgrade.py:404
msgid ""
"Before you continue ensure that your system is fully upgraded by running "
"\"dnf --refresh upgrade\". Do you want to continue"
msgstr ""
"Przed kontynuacją należy upewnić się, że system jest całkowicie "
"zaktualizowany wykonując polecenie „dnf --refresh upgrade”. Kontynuować?"

#: ../plugins/system_upgrade.py:408
msgid "Operation aborted."
msgstr "Przerwano działanie."

#: ../plugins/system_upgrade.py:472
msgid "system is not ready for upgrade"
msgstr "system nie jest gotowy na aktualizację"

#: ../plugins/system_upgrade.py:474
msgid "upgrade is already scheduled"
msgstr "aktualizacja jest już zaplanowana"

#: ../plugins/system_upgrade.py:480
msgid "trigger file does not exist. exiting quietly."
msgstr "plik wyzwalacza nie istnieje. Ciche kończenie działania."

#: ../plugins/system_upgrade.py:483
msgid "another upgrade tool is running. exiting quietly."
msgstr ""
"inne narzędzie do aktualizacji systemu jest uruchomione. Ciche kończenie "
"działania."

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:489
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr "polecenie „dnf system-upgrade reboot” rozpocznie aktualizację systemu"

#: ../plugins/system_upgrade.py:506
msgid "Rebooting to perform upgrade."
msgstr "Ponowne uruchamianie, aby wykonać aktualizację."

#: ../plugins/system_upgrade.py:528 ../plugins/system_upgrade.py:534
msgid "Starting system upgrade. This will take a while."
msgstr "Rozpoczynanie aktualizacji systemu. Może to chwilę zająć."

#: ../plugins/system_upgrade.py:559 ../plugins/system_upgrade.py:568
#, python-format
msgid "Unable to match package: %s"
msgstr "Nie można dopasować pakietu: %s"

#: ../plugins/system_upgrade.py:573
msgid "Unable to match some of packages"
msgstr "Nie można dopasować części pakietów"

#: ../plugins/system_upgrade.py:576
msgid "Cleaning up downloaded data..."
msgstr "Czyszczenie pobranych danych…"

#: ../plugins/system_upgrade.py:623
msgid "Download finished."
msgstr "Ukończono pobieranie."

#: ../plugins/system_upgrade.py:627 ../plugins/system_upgrade.py:628
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "Ukończono aktualizację systemu. Czyszczenie i ponowne uruchamianie…"

#: ../plugins/tracer.py:70
msgid "For more information run:"
msgstr "Więcej informacji:"

#: ../plugins/tracer.py:97
msgid "Call to Tracer API ended unexpectedly:"
msgstr "Wywołanie do API Tracer nieoczekiwanie zakończyło działanie:"

#: ../plugins/tracer.py:99
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""
"Proszę zgłosić błąd na stronie https://github.com/FrostyX/tracer/issues "
"(w języku angielskim)"

#: ../plugins/tracer.py:101
msgid "We apologize for any inconvenience"
msgstr "Przepraszamy za niedogodności"

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "połączenie ze snapperd się nie powiodło: %s"

#: ../plugins/snapper.py:55
msgid "creating pre_snapshot"
msgstr "tworzenie „pre_snapshot”"

#: ../plugins/snapper.py:61
#, python-format
msgid "created pre_snapshot %d"
msgstr "utworzono „pre_snapshot” %d"

#: ../plugins/snapper.py:65
#, python-format
msgid "creating pre_snapshot failed: %s"
msgstr "utworzenie „pre_snapshot” się nie powiodło: %s"

#: ../plugins/snapper.py:74
msgid "skipping post_snapshot because creation of pre_snapshot failed"
msgstr ""
"pomijanie „post_snapshot”, ponieważ utworzenie „pre_snapshot” się nie "
"powiodło"

#: ../plugins/snapper.py:80
msgid "creating post_snapshot"
msgstr "tworzenie „post_snapshot”"

#: ../plugins/snapper.py:85
#, python-format
msgid "created post_snapshot %d"
msgstr "utworzono „post_snapshot” %d"

#: ../plugins/snapper.py:89
#, python-format
msgid "creating post_snapshot failed: %s"
msgstr "utworzenie „post_snapshot” się nie powiodło: %s"
